# Generated by Django 6.0.4 on 2026-04-22 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre completo')),
                ('email', models.EmailField(max_length=254, verbose_name='Correo electrónico')),
                ('telefono', models.CharField(max_length=20, verbose_name='Teléfono')),
                ('tipo_evento', models.CharField(choices=[('casamiento', 'Casamiento'), ('cumpleanos', 'Cumpleaños'), ('corporativo', 'Evento Corporativo'), ('bautismo', 'Bautismo'), ('otro', 'Otro')], default='casamiento', max_length=20, verbose_name='Tipo de evento')),
                ('fecha_evento', models.DateField(verbose_name='Fecha tentativa del evento')),
                ('cantidad_invitados', models.PositiveIntegerField(verbose_name='Cantidad de invitados aproximada')),
                ('mensaje', models.TextField(help_text='Cuéntenos sobre su evento soñado...', verbose_name='Mensaje o consulta')),
                ('fecha_consulta', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Consulta',
                'verbose_name_plural': 'Consultas',
                'ordering': ['-fecha_consulta'],
            },
        ),
    ]
