# Generated by Django 6.0.4 on 2026-06-23 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='consulta',
            name='categoria',
            field=models.CharField(choices=[('Comercial', 'Consulta Comercial'), ('Técnica', 'Consulta Técnica'), ('RRHH', 'Consulta de RRHH'), ('General', 'Consulta General'), ('Pendiente', 'Pendiente de Clasificación')], default='Pendiente', max_length=20, verbose_name='Categoría de la consulta'),
        ),
    ]
